# docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: ${env}
      DB_HOST: db
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
      DB_POOL: 5
    volumes:
      - .:/usr/src/blog

volumes:
  postgres-data:

